mucsci-students/2024sp-420-PythonB

classadd.py
Please go through add class, rename class and delete class function.
=> Name Class

Test/test_classadd.py
I fixed the orders of the parameters when adding methods and fields based on client preference. I also switched the order of the parameters when adding a parameter because I would expect he would want the format of that to match fields and methods
=> Class pytest

Models/attribute.py, Models/classadd.py, Models/errorHandler.py, Models/relationship.py, controller.py
Created errorHandler.py...
Modify the classadd.py and controller.py to get the function calls working... 
Added method class with pydoc...
=> Some updates

Models/attribute.py, Models/classadd.py, Models/relationship.py, Test/test_classadd.py, Test/test_methods.py, Test/test_relationship.py
remove all error handler decorators...
fix the syntax error in Fields Class...
modify test_classadd.py...
add test_methods.py...
=>  Add method test and other minor changes

Models/attribute.py, Models/classadd.py, Models/diagram.py, Models/saveload.py, Views/cli.py, controller.py
This is pretty hefty and I apologize
=> controller and view updated/split, attribute changes accounted for

src/Controllers/cli_controller.py, src/Controllers/controller.py, src/Controllers/gui_controller.py, src/Views/cli_view.py
- Removed autocomplete from view into controller
- Tested autocomplete functionality is working as intended with new integration
- Added documentation for modified/added methods
=> Smart input

.github/workflows/python-app.yml, README.md, main.py
- Tested GitHub Actions on this branch *All tests passing*
- Builds project, runs tests, and shows the code coverage within src/models
=> Continuous Integration

src/Models/uml_class.py, src/tests/class_test.py
Add position to uml_class in Model
=> Add position property for uml_class

src/Models/uml_diagram.py, src/Models/uml_relation.py, src/Models/uml_save_load.py, src/schema/draft07.json, src/tests/diagram_test.py, src/tests/relation_test.py, src/tests/save_load_test.py, src/tests/undo_redo_test.py
Add schema validate for save_load.
Fix bugs caused by not matching schema requirements.
Download draft07schema due to unable to find it when testing.
=> schema validate

src/Views/gui_view.py
Some minor clean up.
Some of this *may* break when the backend is hooked in, but I have tested it else where and it works.
=> Drop Downs for Relation stuff.

src/Controllers/cli_controller.py, src/Controllers/controller.py, src/Controllers/gui_controller.py, src/Views/gui_view.py
Move update functionality to UML_Controller.
Add draw functions to be able to draw the diagram in each iteration of main loop.
Add related functions to GUI_View to simulate draw and listen.
=> Gui controller

src/Controllers/controller.py, src/Views/cli_view.py
- Fixed param related typos in help menu
- Added types to help menu
- add help menu types to autocompletion
- Replaced exit with quit within autocompletion
- Added save and quit functionality with simple valid filename verification
- **Save and Quit functionality fully tested and working**
=> Small fixes!

src/Views/gui_view.py
Rearranged init order to allow checks
Buttons should only appear based on number of class boxes that exist. This will either need to delete and recreate the sidebar, or if we clearing and restarting the view each time, that would take care of it.
Made Class_Box a class withing the view in order to make things more stream lined
Recreate_Class_Box was created in part of my attempt to get move working. May not need, but I'm keeping it until I know one way or the other.
=> Partial Progress on GUI stuff

src/Views/gui_view.py
Class Boxes are moveable.
They will still need more info put into them, (fields, methods, etc)
Uncommented out relation button condition to make sure the functionality still worked.
=> G UI moveable cards

src/Views/gui_view.py
Dropdowns to display classes for Add Relation, Add Field, Add Method.
There's a lot of formatting changes, so there isn't actually as many changes as it looks like.
Buttons now dynamically show based on how many classes are on the diagram (Will need opposite logic for delete).
This currently causes the sidebar to switch sides, but I will figure that out later, shouldn't be a difficult change.
=> GUI dropdowns

src/Views/gui_view.py
Added Help Menu
&nbsp;&nbsp;&nbsp;&nbsp;When "View Help" is clicked, it opens a help dialog.
Center the Window during the initial launch of the application
=> Implement Help Menu

src/Views/gui_view.py
=> G UI dropdowns

src/Views/gui_view.py
Follow same process as field delete
=> Method Delete dropdowns

src/Controllers/controller.py, src/Models/uml_class.py, src/Views/gui_view.py, src/tests/class_test.py, src/tests/save_load_test.py
Update save/load position
Still have weird behavior on first drag, but everything else should work fine.
=> Update save/load position

src/Controllers/gui_controller.py, src/Views/gui_view.py
=> Relationship arrows

README.md, src/Views/cli_view.py, src/Views/relation_completer.py
- **RelationCompleter**
- Custom completer for relations that suggests relations after the user has given two classes e.g. add relation c1 c2 (autosuggest)
- **CLIView**
- Removed "generalizations" as the sprint req. for relations is "realization" 
- **Testing**
- Autocomplete for all of the relation cmds has been tested and is working
- Readme steps were tested on windows using a fresh venv
- Note: Readme still needs design pattern short descriptions and file locations added under # Design Patterns
=> AutoComplete and Readme

README.md, src/Models/uml_param.py
readme updates. Pretty sure Tim and I got everything we need
=> Read me edit

src/Controllers/controller.py, src/Controllers/gui_controller.py, src/Views/gui_view.py
Fix and Update all command to use option menu if possible.
Fix bugs.
Add GUI error message display.
=> Gui relation

src/Views/gui_view.py
Param Button was not being enabled when there were two or more classes.
General clean up.
Removed unnecessary comments, outdated comments, added spaces to keep style the same, etc.
=> Param Button Not Enabled.

src/Views/gui_view.py
=> Undo redo fix

src/Views/gui_view.py
Very difficult. Much thought.
Left a TODO/note for myself for later.
=> Tracker Removed

src/Views/gui_view.py
Update GUI to redraw the whole diagram when dragging class boxes
Cleanup
=> Class card dragging fix

src/Views/gui_view.py
Fix extra padding in the class card. 
Remove extra space below methods.
=> Update extra padding in Class_Box

src/Models/uml_class.py, src/Models/uml_diagram.py, src/Views/gui_view.py
- A single self relation can now be added
- Removed unneded import from Diagram
=> Bugfixes and tests

src/Models/uml_class.py, src/Models/uml_diagram.py, src/Models/uml_save_load.py, src/Views/__init__.py, src/Views/cli_view.py, src/Views/uml_list.py, src/tests/abc_test.py, src/tests/class_test.py, src/tests/diagram_test.py, src/tests/fields_test.py, src/tests/method_test.py, src/tests/relation_test.py, src/tests/save_load_test.py
- Moved list visitor to the view because it is for making things look nice on the CLI
- I believe the NotImplementedErrors in the interfaces are unreachable but required by convention.
=> 98% coverage

src/Views/gui_view.py
Dialog Factory about half implemented. I just have to do the some stuff with Fields and Methods, then all of the param stuff.
Will need to do some formatting stuff to make it look nicer, but it functionally works.
Lots of dead code removed.
=> Design pattern

pyproject.toml, src/Views/gui_view.py
- Used `customtkinter` library to give buttons a modern look
-  Made Relationship button clickable if `class_box > 0`
- Field/Method rename/delete buttons are now grayed out if there are not field or method to delete/rename
=> G UI buttons

src/Models/uml_class.py, src/Models/uml_diagram.py, src/Models/uml_image.py, src/Views/gui_view.py, src/tests/image_test.py
Now new class will be added to below the lowest class.
=> Export image

src/Controllers/controller.py, src/Controllers/gui_controller.py, src/Views/gui_view.py
Fix too frequently save_states for dragging event in GUI
=> Fix too frequent save_states for dragging event in GUI

src/Models/uml_image.py
=> Fix export issue

src/Views/gui_view.py
=> Add ctrl+z for undo and ctrl+y for redo

src/Views/gui_view.py
Fix scrollbar enabled when empty
change camera position to int to avoid potential floating point number issues
=> Fix scrollbar issues
